core:
  control:
    - maxAttempts: 3
    - searchPeriod: 7d
    - banPeriod: 1w
  stats:
    enabled: true
    banStats: true
    originStats: true
    credentialStats: true


sshd:
  file: /var/log/auth.log
  parser: sshd
  port: 22
  filters:
  - sshd


