name: Tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test-ubuntu:
    strategy:
      fail-fast: false
      
      matrix:
        include:
          - config: release (gcc)
            variant: Release
            cc: gcc
            cxx: g++
          - config: debug (gcc)
            variant: Debug
            cc: gcc
            cxx: g++

    # The OS to run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: LunarWatcher/install-conan@master
      - name: Install dependencies
        run: |
          sudo apt update && sudo apt upgrade -y
          sudo apt install -y libsystemd-dev
      - name: Check systemd shit
        run: |
          sudo logger -t iliketrains Leeeeeeeeeeeeeeeeeeeeeeeroy jenkins
          sudo journalctl -t iliketrains
      - name: Print versions
        run: |
          ${{ matrix.cxx }} --version
          ${{ matrix.cc }} --version
      - name: Run tests
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.variant }} -DINTEGRATION=ON
          # Not entirely sure how much the GitHub runners support
          make -j $(nproc) test
        env:
          CXX: ${{matrix.cxx}}
          CC: ${{matrix.cc}}
  valgrind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install deps
        run: |
          sudo apt update && sudo apt upgrade -y
          sudo apt install -y libsystemd-dev valgrind 
      - name: Build tests
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make -j $(nproc) tests
      - name: Run tests
        run: |
          valgrind --leak-check=yes ./bin/tests
        working-directory: build



