name: Tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test-ubuntu:
    strategy:
      fail-fast: false
      
      matrix:
        # Config: contains the system setup.
        config:
          - release
          - debug

        include:
          - config: release
            variant: Release
          - config: debug
            variant: Debug

    # The OS to run on
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: LunarWatcher/install-conan@master
      - name: Run tests
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.variant }}
          # Not entirely sure how much the GitHub runners support
          make
          ./bin/tests

